### PR TITLE
Add Note and interval information to chord image

### PR DESCRIPTION
**Pull request by l03wn3**
When looking at chord charts, it is useful to not only get information about suggested finger placement, but also about what actual notes the placements give, as well as information about which interval that note is to the root of the chord. 

This PR:
* Adds Note information to chord image
* Adds Interval information to chord image
* Refactors out the Chord model into a separate class
* Adds unit tests to Chord class

Examples:
Org:
orggmin7
to
gmin7

and
dorg
to
d

Screenshot of the UI:
screenshot

### CODE REVIEW

**Comment by psifidotos** [comment]
@l03wn3 can you show a screenshot of your proposal?

**Comment by l03wn3** [comment]
Of course! Updated the PR description.

**Comment by l03wn3** [comment]
I Noticed that in the top screenshot, distances are a bit off between the top text and the chord box. Will fix and update PR.

Also the distance between the chord name and the chord box is too great and will be fixed.

**Comment by psifidotos** [comment]
Just to add , the original version is the classic met in bibliography... Any changes / additions to the original should be optional! but I will wait the author to show its opinion

**Comment by l03wn3** [comment]
Great input @psifidotos! Is there a standardised way to note chord? I've drawn inspiration from my jazz literature. I can certainly make this change optional by a user interface option.

**Comment by l03wn3** [comment]
The expanded info is now behind a checkbox. If not checked, the original appearance will be generated.

**Comment by gzur** [comment]
Development of the ChordImageGenerator has moved to [rluetzner/ChordImageGenerator](https://github.com/rluetzner/ChordImageGenerator)

Closing this before archiving the repository.

**Pull request closed without merging**
